### PR TITLE
✨ Add foreign key support

### PR DESCRIPTION
**Pull request by matheusvellone**
Adding Foreign Key support, which will add a black key icon

image

### CODE REVIEW

**Review by PillFall — CHANGES_REQUESTED** [review]
Nice, this could be a great new feature to the Widget.

There are only two things I want you to check before merging this PR.

- I know I still do not have contributing guide and code / commit styling, but I want the commits to have an according [gitmoji](https://gitmoji.dev), and start capitalized, without end dot. (Required)
- What do you think about changing the icon for the foreign key to a `link` ( ) and the color, maybe, to violet (`#9747ff`), to make it unique and more accessible for color-blind people?

**Comment by matheusvellone** [comment]
Sure! Working on that right now. I'll ammend my changes to the renamed commit in a few minutes

**Comment by matheusvellone** [comment]
There is it! 😄 

image

**Review by PillFall — CHANGES_REQUESTED** [review]
Perfect 😊, But there is still one thing missing, the first word in the subject must be capitalized 😥.

**Review by PillFall — APPROVED** [review]
All right, now I'll merge it in a while. Thanks for taking the time to upgrade this Widget 😊

**Comment by PillFall** [comment]
Now is merged, there was a commit mismatch as I amend the commit subject 😢

**Comment by PillFall** [comment]
Sorry if I force push a new commit into your branch, but as it would probably be annoying to ask for changes, I decided to do it myself.

I change the message commit from `:sparkles:` to `✨`(An actual Unicode emoji) I forgot to mention, that I want it to be Unicode for shell support (not only GitHub).

**Comment by PillFall** [comment]
If you want me to revert and redo the merges, let me know

**Pull request merged**
